name: 'Inject KernelSU'
description: 'Downloads and patches standard KernelSU'
runs:
  using: "composite"
  steps:
    - name: Inject KernelSU
      shell: bash 
      working-directory: "KernelSU"
      run: |
        echo "Injecting KernelSU setup script..."
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

        git fetch --unshallow > /dev/null 2>&1 || true
        
        KSU_TAG=$(git describe --abbrev=0 --tags)
        echo "ROOT_TAG=$KSU_TAG" >> $GITHUB_ENV
        KSU_MAJOR=$(echo "$KSU_TAG" | sed -E 's/^v([0-9]+).*/\1/')
        KSU_GIT_COUNT=$(git rev-list --count HEAD)
        
        KSU_DYNAMIC_VERSION=$(( (KSU_MAJOR * 10000) + KSU_GIT_COUNT ))
        echo "Calculated Version Code: $KSU_DYNAMIC_VERSION"
        echo "Bypassing sandbox bug by patching dynamic version..."
        sed -i "s/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=$KSU_DYNAMIC_VERSION/g" kernel/Kbuild
