name: 'Publish Kernel Release'
description: 'Uploads compiled kernel files to GitHub Releases.'

inputs:
  device_name:
    description: 'The name of the device'
    required: true
  kernel_version:
    description: 'The firmware string'
    required: true
  files_path:
    description: 'The folder containing all downloaded matrix artifacts'
    required: true
    default: 'final-release-files/*'

runs:
  using: "composite"
  steps:
    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "${{ inputs.device_name }}-${{ inputs.kernel_version }}"
        name: "${{ inputs.device_name }} - ${{ inputs.kernel_version }}"
        body: |
          Automated kernel build for the **${{ inputs.device_name }}**.
          **Firmware Base:** `${{ inputs.kernel_version }}`
          ### Included Files
          All successfully compiled variants are attached below. The files are dynamically named to reflect their root implementation and version.
          *Note: Extract and pack the respective `.gz` image with your `boot.img` using tools like magiskboot.*
        draft: false
        prerelease: false
        files: ${{ inputs.files_path }}
