name: Build Samsung A06 (SM-A06F) - KernelSU

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  watchdog:
    name: Check for KernelSU Updates
    runs-on: ubuntu-22.04
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Compare Release Tags
        id: check
        run: |
          echo "Fetching latest official KernelSU release..."
          OFFICIAL_TAG=$(curl -sL https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r '.tag_name')
          
          echo "Constructing expected local tag..."
          MY_EXPECTED_TAG="KernelSU-$OFFICIAL_TAG"
          
          echo "Fetching the latest release from repository ..."
          MY_LATEST_TAG=$(gh release list --limit 100 | awk '{print $1}' | grep "^KernelSU-" | head -n 1)
          # MY_LATEST_TAG=$(curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #   "https://api.github.com/repos/${{ github.repository }}/releases" | \
          #   jq -r '[.[] | select(.tag_name | startswith("KernelSU-"))][0].tag_name')
          
          if [ "$MY_LATEST_TAG" == "null" ]; then
            MY_LATEST_TAG="None"
          fi
          
          echo "Official Latest: $OFFICIAL_TAG"
          echo "My Latest: $MY_LATEST_TAG"
          
          if [ "$MY_EXPECTED_TAG" == "$MY_LATEST_TAG" ]; then
            echo "Versions match. No new KernelSU update found. Canceling build."
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "Mismatch detected! A new version is available. Triggering build."
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi
          
  build_execution:
    name: KernelSU Build 
    needs: watchdog
    if: ${{ needs.watchdog.outputs.should_build == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/core-compiler.yml
    with:
      variant_name: "KernelSU"
      setup_url: "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh"
      patch_script: |
        echo "Change directory to KernelSU directory..."
        cd KernelSU
              
        git fetch --unshallow > /dev/null 2>&1 || true
        
        KSU_TAG=$(git describe --abbrev=0 --tags)
        echo "ROOT_TAG=$KSU_TAG" >> $GITHUB_ENV
        KSU_MAJOR=$(echo "$KSU_TAG" | sed -E 's/^v([0-9]+).*/\1/')
        KSU_GIT_COUNT=$(git rev-list --count HEAD)
        
        KSU_DYNAMIC_VERSION=$(( (KSU_MAJOR * 10000) + KSU_GIT_COUNT ))
        echo "Calculated Version Code: $KSU_DYNAMIC_VERSION"
        echo "Bypassing sandbox bug by patching dynamic version..."
        sed -i "s/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=$KSU_DYNAMIC_VERSION/g" kernel/Kbuild
        
        cd ..
    secrets: inherit
