name: Build Samsung A06 (SM-A065F) - KernelSU

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  watchdog:
    name: Check for KernelSU Updates
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Compare Release Tags
        id: check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: ./.github/actions/00-check-update/kernelsu
          
  build-execution:
    name: KernelSU Build
    needs: watchdog
    if: ${{ needs.watchdog.outputs.should-build == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/core-compiler.yml
    with:
      variant-name: "KernelSU"
    secrets: inherit
