name: Build Samsung A06 (SM-A065F) - KernelSU

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  watchdog:
    name: Check for KernelSU Updates
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Compare Release Tags
        id: check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: ./.github/actions/check-update/kernelsu
          
  build-execution:
    name: KernelSU Build
    needs: watchdog
    if: ${{ needs.watchdog.outputs.should-build == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/core-compiler.yml
    with:
      variant-name: "KernelSU"
      setup-url: "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh"
      patch-script: |
        git fetch --unshallow > /dev/null 2>&1 || true
        
        KSU_TAG=$(git describe --abbrev=0 --tags)
        echo "ROOT_TAG=$KSU_TAG" >> $GITHUB_ENV
        KSU_MAJOR=$(echo "$KSU_TAG" | sed -E 's/^v([0-9]+).*/\1/')
        KSU_GIT_COUNT=$(git rev-list --count HEAD)
        
        KSU_DYNAMIC_VERSION=$(( (KSU_MAJOR * 10000) + KSU_GIT_COUNT ))
        echo "Calculated Version Code: $KSU_DYNAMIC_VERSION"
        echo "Bypassing sandbox bug by patching dynamic version..."
        sed -i "s/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=$KSU_DYNAMIC_VERSION/g" kernel/Kbuild        
    secrets: inherit
