name: Build Samsung A06 (SM-A065F) - KernelSU-Next

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  watchdog:
    name: Check for KernelSU-Next Updates
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - name: Compare Release Tags
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Fetching latest official KernelSU-Next release..."
          OFFICIAL_TAG=$(curl -sL https://api.github.com/repos/rifsxd/KernelSU-Next/releases/latest | jq -r '.tag_name')
          
          echo "Constructing expected local tag..."
          MY_EXPECTED_TAG="KernelSU-Next-$OFFICIAL_TAG"
          
          echo "Fetching the latest release from your repository..."
          MY_LATEST_TAG=$(gh release list -R ${{ github.repository }} --limit 100 --json tagName --jq '.[].tagName' | grep -E "^KernelSU-Next-v?[0-9]" | head -n 1)
          
          if [ "$MY_LATEST_TAG" == "null" ]; then
            MY_LATEST_TAG="None"
          fi
          
          echo "Official Latest: $OFFICIAL_TAG"
          echo "My Latest: $MY_LATEST_TAG"
          
          if [ "$MY_EXPECTED_TAG" == "$MY_LATEST_TAG" ]; then
            echo "Versions match. No new KernelSU-Next update found. Canceling build."
            echo "should-build=false" >> $GITHUB_OUTPUT
          else
            echo "Mismatch detected! A new version is available. Triggering build."
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi
          
  build_execution:
    name: KernelSU-Next Build 
    needs: watchdog
    if: ${{ needs.watchdog.outputs.should-build == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/core-compiler.yml
    with:
      variant-name: "KernelSU-Next"
      setup-url: "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh"
      project-path: './KernelSU-Next'
      patch-script: |
        git fetch --unshallow > /dev/null 2>&1 || true
        
        KSUN_TAG=$(git describe --abbrev=0 --tags)
        echo "ROOT_TAG=$KSUN_TAG" >> $GITHUB_ENV
        KSUN_MAJOR=$(echo "$KSUN_TAG" | sed -E 's/^v([0-9]+).*/\1/')
        KSUN_GIT_COUNT=$(git rev-list --count HEAD)
        
        KSUN_DYNAMIC_VERSION=$(( (KSUN_MAJOR * 10000) + KSUN_GIT_COUNT ))
        echo "Calculated Version Code: $KSUN_DYNAMIC_VERSION"
        echo "Bypassing sandbox bug by patching dynamic version..."
        sed -i "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSUN_DYNAMIC_VERSION/g" kernel/Kbuild
        sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSUN_TAG/g" kernel/Kbuild
    secrets: inherit
