name: Build Samsung A06 (SM-A065F)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  watchdog:
    name: Check for Updates
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    
      - name: Compare Release Tags
        id: check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: ./.github/actions/00-check-update/kernelsu
          
  build:
    name: Build Execution
    needs: watchdog
    if: |
      ${{
        needs.watchdog.outputs.should-build == 'true' ||
        github.event_name == 'workflow_dispatch'
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        
      # 2. Clean up the runner
      - name: Free Runner Disk Space
        uses: ./.github/actions/01-cleanup-runner
        
      # 3. Install Build Dependencies
      - name: Install Build Dependencies
        uses: ./.github/actions/02-install-dependencies
        
      # 4. Securely pull Kernel.tar.gz and toolchain.tar.gz
      - name: Fetch Samsung A06 (SM-A065F) Kernel Source and Toolchain
        uses: ./.github/actions/03-fetch-sources/sm-a065f

      # 5. Handle double extraction & drop intermediate archives instantly
      - name: Extract Samsung Kernel and toolchain archives
        uses: ./.github/actions/04-prepare-sources

      # 6. Configure JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          java-version: '21'
          distribution: 'temurin'

      # 7. Merge Samsung Toolchain
      - name: Merge Samsung Toolchain
        uses: ./.github/actions/05-merge-toolchain
          
      # 8. Automatically patch the kernel tree for root implementation
      - name: Inject Root Implementation
        uses: ./.github/actions/06-inject-root
          
      # 9. Fire off the original wrapper script provided by Samsung
      - name: Execute Samsung Kernel Build
        uses: ./.github/actions/07-run-build/samsung

      # 10. Gather the final kernel binary and .ko modules files
      - name: Prepare Files for Release
        uses: ./.github/actions/08-prepare-release

      # 11. Upload directly to GitHub Releases
      - name: Publish to GitHub Releases
        uses: ./.github/actions/09-publish-release
